spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_social_network
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: syedaliahsan2002@gmail.com
    password: bvxd slya nqnm fyvu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

  application:
    security:
      jwt:
        secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
        expiration: 8640000

    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account
    file:
      upload:
        photos-output-path: ./uploads
#        cover-photo-path: ./uploads/coverPhotos
#        posts-output-path: ./uploads/posts

server:
  port: 8088
