name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  backend:
    name: Backend - Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: book-social-network/book-netwok-api
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'
      - name: Test
        run: mvn -B -ntp test

  frontend:
    name: Frontend - Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontEnd/Book-network-ui
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontEnd/Book-network-ui/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build -- --configuration production
      - name: Unit tests (ChromeHeadless)
        run: npm test -- --watch=false --browsers=ChromeHeadless
